baseURL = "https://ilo.projects.metio.wtf/"
languageCode = "en"
theme = "metio"
title = "ilo"

pygmentsUseClasses=true
sectionPagesMenu = "main"
enableRobotsTXT = true
DefaultContentLanguage = "en"

[outputs]
  home = [ "HTML", "RSS", "ATOM", "HUMANS", "FOAF"]
  section = ["HTML", "RSS", "ATOM"]
  term = ["HTML", "RSS", "ATOM"]

[params]
  mainSections = ["community", "compose", "contributors", "devcontainer", "integration", "metrics", "shell", "usage"]
  author = "metio.wtf"
  email = "https://metio.groups.io/g/ilo/topics"
  matrix = "#ilo:matrix.org"
  github = "metio/ilo"
  mastodon = "https://fosstodon.org/@metiobuild"
  work = "ilo.projects.metio.wtf"
  description = "manage reproducible build environments"
