name: Perform Release
on:
  schedule:
    - cron:  '45 3 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # SonarQube: Disabling shallow clone is recommended for improving relevancy of reporting
          # Hugo: Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.4
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create Release Version
        id: release
        run: echo "::set-output name=version::$(date +'%Y.%-m.%-d-%-H%M%S')"
      - name: Count commits in last week
        id: commits
        run: echo "::set-output name=count::$(git rev-list --count HEAD --since='last Sunday')"
      - name: Verify Project
        run: mvn --batch-mode --settings $GITHUB_WORKSPACE/build/settings.xml verify -Drevision=${{ steps.release.outputs.version }} -Dskip.graal=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        if: steps.commits.outputs.count > 0
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.version }}
          release_name: Release ${{ steps.release.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Automated release, see [commits](https://github.com/metio/ilo/commits/${{ steps.release.outputs.version }}) for changes.
      - name: Upload Java11 Artifact
        if: steps.commits.outputs.count > 0
        id: upload-java11-artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/ilo-${{ steps.release.outputs.version }}-java11.zip
          asset_name: ilo-${{ steps.release.outputs.version }}-java11.zip
          asset_content_type: application/zip
      - name: Upload Java11 Checksum
        if: steps.commits.outputs.count > 0
        id: upload-java11-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/ilo-${{ steps.release.outputs.version }}-java11.zip.sha512
          asset_name: ilo-${{ steps.release.outputs.version }}-java11.zip.sha512
          asset_content_type: text/plain
      - name: Upload Native Unix Artifact
        if: steps.commits.outputs.count > 0
        id: upload-native-unix-artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/ilo-${{ steps.release.outputs.version }}-native-unix.zip
          asset_name: ilo-${{ steps.release.outputs.version }}-native-unix.zip
          asset_content_type: application/zip
      - name: Upload Native Unix Checksum
        if: steps.commits.outputs.count > 0
        id: upload-native-unix-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/ilo-${{ steps.release.outputs.version }}-native-unix.zip.sha512
          asset_name: ilo-${{ steps.release.outputs.version }}-native-unix.zip.sha512
          asset_content_type: text/plain
      - name: Send Mail
        if: steps.commits.outputs.count > 0
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ilo release ${{ steps.release.outputs.version }}
          body: See https://github.com/metio/ilo/releases/tag/${{ steps.release.outputs.version }} for details.
          to: ilo@metio.groups.io
          from: ${{ secrets.MAIL_SENDER }}
      - name: Publish Toot
        if: steps.commits.outputs.count > 0
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_TOKEN }}
          message: "#ilo version ${{ steps.release.outputs.version }} published! https://github.com/metio/ilo/releases/tag/${{ steps.release.outputs.version }} #metio"
          host: ${{ secrets.MASTODON_SERVER }}
      - uses: BjornLuG/release-for-reddit-action@v1
        if: steps.commits.outputs.count > 0
        with:
          username: ${{ secrets.REDDIT_USERNAME }}
          password: ${{ secrets.REDDIT_PASSWORD }}
          app-id: ${{ secrets.REDDIT_APP_ID }}
          app-secret: ${{ secrets.REDDIT_API_SECRET }}
          subreddit: ${{ secrets.REDDIT_SUBREDDIT }}
          url: https://github.com/metio/ilo/releases/tag/${{ steps.release.outputs.version }}
