name: REUSE Compliance Check
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
