name: Verify
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: GraalVM Setup
        uses: rinx/setup-graalvm-ce@v0.0.4
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - uses: actions/cache@v1
        name: Cache Maven Repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: gpg-key
        name: Import GPG Key
        run: |
          cat <(echo -e "${{ secrets.GPG_KEY }}") | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Build with Maven
        run: mvn --batch-mode --settings $GITHUB_WORKSPACE/build/settings.xml verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
